---
- name: ping module
  hosts: sftp
  become: True 
  vars:
    username: sE00_PAT_ans
  tasks:
    - name: just display
      shell: uptime
    - name: Ensure group "somegroup" exists
      group:
        name: ansible
        state: present
    - name: create remote user user1 and add to wheel group
      user:
        name: sE00_PAT_ans
        groups: ansible
        append: yes
        state: present
    - name: Allow 'ansible' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        backup: yes
        #regexp: '^%wheel'
        line: '%ansible ALL=(ALL) NOPASSWD: ALL'
    - name: Create the .ssh  directory if it does not exist
      file:
        path: /home/sE00_PAT_ans/.ssh
        state: directory
        mode: '0700'
        owner: sE00_PAT_ans
        group: sE00_PAT_ans
    - name: copy the pub file to authorized_keys
      copy:
        src: /home/admin/ansible.pub
        dest: /home/sE00_PAT_ans/.ssh/authorized_keys
        mode: 0640
        owner: sE00_PAT_ans
        group: sE00_PAT_ans
    - name: Add User to AllowUsers
      lineinfile: 
        dest: /etc/ssh/sshd_config
        backup: yes
        backrefs: yes
        state: present
        regexp: '^AllowUsers((?:(?:\s+\S+(?!\S))(?<!\s{{ username }}))+\s*?)(\n?)$'
        line: 'AllowUsers\1 {{ username }}\2'
    - name: reload sshd
      service:
        name: sshd
        state: reloaded
